name: PR checks

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Syntax check all PHP files
        run: |
          set -e
          mapfile -t files < <(git ls-files '*.php')
          for f in "${files[@]}"; do
            php -l "$f"
          done
